// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package testlib;

@net.sf.jni4net.attributes.ClrType
public class Test extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected Test(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public Test() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        testlib.Test.__ctorTest0(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorTest0(net.sf.jni4net.inj.IClrProxy thiz);
    
    public static system.Type typeof() {
        return testlib.Test.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        testlib.Test.staticType = staticType;
    }
    //</generated-proxy>
}
